language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: Lq9Gm9ZdDbYJ79+YwBPMmA3LXEl/LYBP9N+XDVZqXjNkpIOsdgQNsuNRVl4c0tGW9LBal+3OGQotQ8VhE3R0xg6YJ3l0pZb5f3T1zJLbh9AWIb9U6bzFKANSXBYIcpMgmmmR5/94CbG8AalqbzE6JhJpJ/w4qFoyu61Z7FGN0a5vvlzBLq9ohVuPaVVlwurM4mBAG3WECZ4mQ9SHAXGhM4nT15WPHLVOXCH+Y5blDv1jeb23kBYbs9wbfffXShYKau3aLOqdyDHEibnQL9bNmRq+eLD9xr+f5S/7XtFOmBS8KkSiTvShZTZwDUju6Y8yDu/uFpA5KoLGIQ6dQ29ehpPMP5gkF0/6rL6DyaEdXVqqmG6r7lgtOVHmtKCncxu7r47+tauB+10pHR4w8RgkFFI//sIhE7MXREUzykVz47vVpmKoF8x66vWFdtirL4HPSSU0l7Etp1QmMb4jacsUHDvEDp5Dy8s3z4BkfusWvrwQR2l9aVj8X4kIxuMOe8hq3yUFOuaevciuagNpE3hlMenX4lwRD08d+CmJNDv65qomJEJFEAWXkDtCwDZmbEas3ycbYVKP7myntGsr/aXD7S1N9OKGKyvzvpZvXrD6NGvrTPZtSiVGsWszXZFIxyVgS/Xap1dzcZ9aW4hrHq1F0z9LMU4rKG0EtM9oNQMyIuc=
  app: jmaxwell-fullstack-server
  on:
    repo: maxjeffwell/full-stack-capstone-server
